version: "3"

services:
  wp-db:
    image: "postgres"
    container_name: "EMT2025_eshop"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=e-shop
    ports:
#      prvoto go menjas
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data